apiVersion: v1
kind: Service
metadata:
  name: postgresdb-service
  namespace: tasklistapp
  labels:
    app: postgresdb
    tier: database
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresdb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: tasklistapp
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    app: postgresdb
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
