apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: tasklistapp
  labels:
    app: tasklistapp
    tier: database
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: tasklistapp-postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: tasklistapp
    app.kubernetes.io/managed-by: argocd
data:
  # PostgreSQL configuration
  POSTGRES_DB: "tasklistdb"
  POSTGRES_USER: "postgres"
  # The password will be set from a secret
  
  # Initialize the database with our schema
  init.sql: |
    CREATE TABLE IF NOT EXISTS tasks (
      id SERIAL PRIMARY KEY,
      title VARCHAR(255) NOT NULL,
      description TEXT,
      completed BOOLEAN DEFAULT false,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
    
    -- Add any additional initialization SQL here
