services:
  # PostgreSQL Database Service
  tasklist-postgres:
    image: postgres:16
    container_name: tasklist-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tasklistdb
    ports:
      - "5432:5432"      # Expose port to host for WSL access
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasklistdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot API Service
  tasklist-api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: tasklist-api
    ports:
      - "8080:8080"
    environment:
      # Database connection variables
      DB_URL: jdbc:postgresql://tasklist-postgres:5432/tasklistdb
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      # JPA Configuration
      JPA_DDL_AUTO: create
      JPA_SHOW_SQL: true
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      tasklist-postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
