apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklistapp-deployment
  namespace: tasklistapp
  labels:
    app: tasklistapp
    tier: backend
    app.kubernetes.io/name: tasklistapp-backend
    app.kubernetes.io/instance: tasklistapp-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: tasklistapp
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: tasklistapp
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: tasklistapp
        tier: backend
        app.kubernetes.io/name: tasklistapp-backend
        app.kubernetes.io/instance: tasklistapp-backend
        app.kubernetes.io/version: "1.0.0"
    spec:
      serviceAccountName: tasklistapp-sa
      containers:
      - name: tasklistapp
        image: ghcr.io/slmakomazi/tasklistapp:api-latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://tasklistapp-postgresql-service:5432/tasklistdb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tasklistapp-secrets
              key: db-password
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_LIQUIBASE_ENABLED
          value: "true"
        - name: SPRING_LIQUIBASE_CHANGE_LOG
          value: "classpath:db/changelog/db.changelog-master.xml"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "validate"
        - name: SPRING_JPA_OPEN_IN_VIEW
          value: "false"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: "org.hibernate.dialect.PostgreSQLDialect"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
          value: "true"
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        - name: SPRING_SQL_INIT_MODE
          value: "always"
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "health,info,metrics"
        - name: MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS
          value: "always"
        - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
          value: "true"
        - name: MANAGEMENT_HEALTH_LIQUIBASE_ENABLED
          value: "true"
        - name: MANAGEMENT_HEALTH_DB_ENABLED
          value: "true"
        - name: MANAGEMENT_HEALTH_DISKSPACE_ENABLED
          value: "true"
        - name: MANAGEMENT_HEALTH_PING_ENABLED
          value: "true"
        - name: MANAGEMENT_HEALTH_READINESSSTATE_ENABLED
          value: "true"
        - name: MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED
          value: "true"
        envFrom:
        - configMapRef:
            name: tasklistapp-config
        - secretRef:
            name: tasklistapp-secrets
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30  # Allow up to 5 minutes for startup (30 * 10s)
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120  # Wait for startup to complete
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90   # Application takes ~106s to start
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
