apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: tasklistapp
  labels:
    app: tasklistapp
    tier: backend
    app.kubernetes.io/name: tasklistapp-backend
    app.kubernetes.io/instance: tasklistapp-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: tasklistapp
    app.kubernetes.io/managed-by: argocd
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: tasklistapp
    tier: backend
  type: ClusterIP
