apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklistapp-deployment
  namespace: tasklistapp
  labels:
    app: tasklistapp
    app.kubernetes.io/name: tasklistapp
    app.kubernetes.io/instance: tasklistapp
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: tasklistapp
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: tasklistapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: tasklistapp
        app.kubernetes.io/name: tasklistapp
        app.kubernetes.io/instance: tasklistapp
        app.kubernetes.io/version: "1.0.0"
    spec:
      serviceAccountName: tasklistapp-sa
      containers:
      - name: tasklistapp
        image: ghcr.io/slmakomazi/tasklistapp:api-latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: tasklistapp-config
        - secretRef:
            name: tasklistapp-secrets
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30  # Allow up to 5 minutes for startup (30 * 10s)
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120  # Wait for startup to complete
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90   # Application takes ~106s to start
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
