apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasklistapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: tasklistapp
    app.kubernetes.io/instance: tasklistapp
spec:
  project: default
  source:
    repoURL: https://github.com/slmakomazi/TasklistApp.git
    targetRevision: HEAD
    path: k8s
    kustomize:
      # Enable kustomize
      version: v4.5.5
      # Add common labels and annotations
      commonAnnotations:
        argocd.argoproj.io/sync-options: PruneLast=true
      commonLabels:
        app.kubernetes.io/name: tasklistapp
        app.kubernetes.io/instance: tasklistapp
        app.kubernetes.io/managed-by: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: tasklistapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # Add sync waves for proper ordering
  # 0: Namespace, CRDs, ServiceAccounts, RBAC
  # 1: ConfigMaps, Secrets
  # 2: Services
  # 3: Deployments, StatefulSets, DaemonSets
  # 4: Ingress, Routes
  # 5: HPA, PDB
  # 6: Jobs, CronJobs
