apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tasklistapp-ingress
  namespace: tasklistapp
  annotations:
    kubernetes.io/ingress.class: "public"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tasklistapp-service
            port:
              number: 80
