apiVersion: v1
kind: ConfigMap
metadata:
  name: tasklistapi-config
  namespace: tasklistapp
data:
  # Application configuration for Kubernetes environment
  LOG_LEVEL_SPRING: "INFO"
  LOG_LEVEL_TASKLIST: "INFO"
  SERVER_PORT: "8080"
  JPA_SHOW_SQL: "false"
  SPRING_PROFILES_ACTIVE: "kubernetes"
  # Database configuration
  SPRING_DATASOURCE_URL: "jdbc:postgresql://tasklistapp-postgresql-service:5432/${DB_NAME}"
  SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
  SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
  # JPA/Hibernate configuration - allows table creation
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  # Spring Boot container optimizations
  SPRING_JMX_ENABLED: "false"
  SPRING_JPA_OPEN_IN_VIEW: "false"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
