name: CI - Build and Push Containers

on:
  workflow_run:
    workflows: ["CI - Test Application"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-containers:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push TaskList API Container
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ghcr.io/slmakomazi/tasklistapp:api-latest
            ghcr.io/slmakomazi/tasklistapp:api-${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push PostgreSQL Database Container
        uses: docker/build-push-action@v5
        with:
          context: ./database
          file: ./database/Dockerfile
          push: true
          tags: |
            ghcr.io/slmakomazi/tasklistapp:db-latest
            ghcr.io/slmakomazi/tasklistapp:db-${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
