name: CI - Test Application

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # PostgreSQL service for integration tests
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    # Environment variables for logging and DB connection (matches application.properties)
    env:
      # Database Configuration (matches application.properties)
      DB_URL: jdbc:postgresql://localhost:5432/testdb
      DB_USERNAME: test
      DB_PASSWORD: test

      # JPA Configuration
      JPA_DDL_AUTO: create-drop
      JPA_SHOW_SQL: true

      # Server Configuration
      SERVER_PORT: 8080

      # Logging Configuration (matches application.properties)
      LOG_LEVEL_SPRING: WARN
      LOG_LEVEL_TASKLIST: DEBUG
      LOG_FILE: test.log

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Unit Tests
        working-directory: ./app
        run: |
          echo "🧪 Running Unit Tests..."
          mvn -B clean test 2>&1 | tee test-output.log
          if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "❌ UNIT TESTS FAILED"
            echo "=== UNIT TEST FAILURES ==="
            grep -E "(FAILURES|ERRORS|Error:|Caused by:|Exception:)" test-output.log | head -20
            echo "=========================="
            exit 1
          else
            echo "✅ Unit tests passed"
          fi

      - name: Run Integration Tests
        working-directory: ./app
        run: |
          echo "🔗 Running Integration Tests..."
          # Environment variables are inherited from the job level (env block above)
          mvn -B test -Dspring.profiles.active=test 2>&1 | tee integration-test-output.log
          if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "❌ INTEGRATION TESTS FAILED"
            echo "=== INTEGRATION TEST FAILURES ==="
            grep -E "(FAILURES|ERRORS|Error:|Caused by:|Exception:)" integration-test-output.log | head -20
            echo "================================"
            exit 1
          else
            echo "✅ Integration tests passed"
          fi
