name: CI - Test Application

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Unit Tests
        working-directory: ./app
        run: |
          echo "🧪 Running Unit Tests..."
          mvn -B clean test 2>&1 | tee test-output.log
          if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "❌ UNIT TESTS FAILED"
            echo "=== UNIT TEST FAILURES ==="
            grep -E "(FAILURES|ERRORS|Error:|Caused by:|Exception:)" test-output.log | head -20
            echo "=========================="
            exit 1
          else
            echo "✅ Unit tests passed"
          fi

      - name: Run Integration Tests
        working-directory: ./app
        run: |
          echo "🔗 Running Integration Tests..."
          mvn -B test -Dspring.profiles.active=test 2>&1 | tee integration-test-output.log
          if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "❌ INTEGRATION TESTS FAILED"
            echo "=== INTEGRATION TEST FAILURES ==="
            grep -E "(FAILURES|ERRORS|Error:|Caused by:|Exception:)" integration-test-output.log | head -20
            echo "================================"
            exit 1
          else
            echo "✅ Integration tests passed"
          fi
