name: Deploy to VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-to-vm:
    runs-on: self-hosted  # VM runs this job directly

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Maven project
        working-directory: ./app
        run: mvn clean package -DskipTests

      - name: Deploy application locally
        run: |
          echo "==========================================="
          echo "📦 Starting Tasklist Deployment"
          echo "==========================================="

          # Prepare deployment directories
          echo "Creating required directories..."
          sudo mkdir -p /opt/tasklist/app
          sudo mkdir -p /opt/tasklist/logs

          # Ensure correct ownership for 'siseko'
          sudo chown -R siseko:siseko /opt/tasklist

          # Stop service if running
          echo "Stopping running service (if exists)..."
          sudo systemctl stop tasklist 2>/dev/null || echo "Service not running"

          # Deploy new JAR
          echo "Copying new JAR..."
          sudo cp app/target/tasklist-api-*.jar /opt/tasklist/app/tasklist-api.jar
          sudo chown siseko:siseko /opt/tasklist/app/tasklist-api.jar

          # Update service file
          echo "Updating systemd service..."
          sudo cp vm/service/tasklist.service /etc/systemd/system/tasklist.service

          # Reload and restart service
          echo "Reloading and restarting service..."
          sudo systemctl daemon-reload
          sudo systemctl enable tasklist
          sudo systemctl restart tasklist

          # Wait and verify
          echo "Verifying deployment..."
          sleep 5
          if sudo systemctl is-active --quiet tasklist; then
            echo "✅ Deployment successful!"
            sudo systemctl status tasklist --no-pager
          else
            echo "❌ Deployment failed! Logs:"
            sudo journalctl -u tasklist -n 20
            exit 1
          fi

          echo "-------------------------------------------"
          echo "📜 Checking application logs..."
          echo "-------------------------------------------"
          sudo tail -n 15 /opt/tasklist/logs/tasklist.log || echo "No logs found yet."
