name: Deploy to VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-to-vm:
    runs-on: self-hosted  # Your VM is now the runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Maven project
        working-directory: ./app
        run: mvn clean package

      - name: Deploy application locally
        run: |
          echo "📦 Starting local deployment on self-hosted runner..."

          # Prepare deployment directory
          sudo mkdir -p /opt/tasklist/app
          sudo mkdir -p /opt/tasklist/logs

          # Stop running service if exists
          echo "Stopping old service (if running)..."
          sudo systemctl stop tasklist 2>/dev/null || echo "Service not running"

          # Copy the new JAR
          echo "Copying new JAR..."
          sudo cp app/target/tasklist-api-*.jar /opt/tasklist/app/tasklist-api.jar

          # Update systemd service if needed
          sudo cp vm/service/tasklist.service /etc/systemd/system/tasklist.service

          # Reload and restart
          echo "Reloading systemd and starting service..."
          sudo systemctl daemon-reload
          sudo systemctl enable tasklist
          sudo systemctl start tasklist

          # Verify
          sleep 5
          if sudo systemctl is-active --quiet tasklist; then
            echo "✅ Deployment successful!"
            sudo systemctl status tasklist --no-pager
          else
            echo "❌ Deployment failed"
            sudo journalctl -u tasklist -n 20
            exit 1
          fi
